"""add summary to post

Revision ID: e303bb0f798e
Revises: ff8e3f08817e
Create Date: 2022-11-05 17:45:47.711574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e303bb0f798e'
down_revision = 'ff8e3f08817e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('summary', sa.Text()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'summary')
    # ### end Alembic commands ###
